// Generated by Neat
//
// This file has been generated
// Do not modify by hand

part of 'dimensions.dart';

// **************************************************************************
// SpaceWidgetsGenerator
// **************************************************************************

class Space1 extends SizedBox {
  const Space1({Key? key})
      : super(
          height: 32,
          width: 32,
          key: key,
        );

  const Space1.w({Key? key})
      : super(
          height: 0,
          width: 32,
          key: key,
        );

  const Space1.h({Key? key})
      : super(
          height: 32,
          width: 0,
          key: key,
        );
}

class Space2 extends SizedBox {
  const Space2({Key? key})
      : super(
          height: 26,
          width: 26,
          key: key,
        );

  const Space2.w({Key? key})
      : super(
          height: 0,
          width: 26,
          key: key,
        );

  const Space2.h({Key? key})
      : super(
          height: 26,
          width: 0,
          key: key,
        );
}

class Space3 extends SizedBox {
  const Space3({Key? key})
      : super(
          height: 18,
          width: 18,
          key: key,
        );

  const Space3.w({Key? key})
      : super(
          height: 0,
          width: 18,
          key: key,
        );

  const Space3.h({Key? key})
      : super(
          height: 18,
          width: 0,
          key: key,
        );
}

class Space4 extends SizedBox {
  const Space4({Key? key})
      : super(
          height: 12,
          width: 12,
          key: key,
        );

  const Space4.w({Key? key})
      : super(
          height: 0,
          width: 12,
          key: key,
        );

  const Space4.h({Key? key})
      : super(
          height: 12,
          width: 0,
          key: key,
        );
}

class Space5 extends SizedBox {
  const Space5({Key? key})
      : super(
          height: 5,
          width: 5,
          key: key,
        );

  const Space5.w({Key? key})
      : super(
          height: 0,
          width: 5,
          key: key,
        );

  const Space5.h({Key? key})
      : super(
          height: 5,
          width: 0,
          key: key,
        );
}

class SpaceBorderRadius1 extends SizedBox {
  const SpaceBorderRadius1({Key? key})
      : super(
          height: 24,
          width: 24,
          key: key,
        );

  const SpaceBorderRadius1.w({Key? key})
      : super(
          height: 0,
          width: 24,
          key: key,
        );

  const SpaceBorderRadius1.h({Key? key})
      : super(
          height: 24,
          width: 0,
          key: key,
        );
}

class SpaceBorderRadius2 extends SizedBox {
  const SpaceBorderRadius2({Key? key})
      : super(
          height: 18,
          width: 18,
          key: key,
        );

  const SpaceBorderRadius2.w({Key? key})
      : super(
          height: 0,
          width: 18,
          key: key,
        );

  const SpaceBorderRadius2.h({Key? key})
      : super(
          height: 18,
          width: 0,
          key: key,
        );
}

class SpaceBorderRadius3 extends SizedBox {
  const SpaceBorderRadius3({Key? key})
      : super(
          height: 12,
          width: 12,
          key: key,
        );

  const SpaceBorderRadius3.w({Key? key})
      : super(
          height: 0,
          width: 12,
          key: key,
        );

  const SpaceBorderRadius3.h({Key? key})
      : super(
          height: 12,
          width: 0,
          key: key,
        );
}

class SpaceBorderSize extends SizedBox {
  const SpaceBorderSize({Key? key})
      : super(
          height: 2,
          width: 2,
          key: key,
        );

  const SpaceBorderSize.w({Key? key})
      : super(
          height: 0,
          width: 2,
          key: key,
        );

  const SpaceBorderSize.h({Key? key})
      : super(
          height: 2,
          width: 0,
          key: key,
        );
}

class SpaceIcon1 extends SizedBox {
  const SpaceIcon1({Key? key})
      : super(
          height: 26,
          width: 26,
          key: key,
        );

  const SpaceIcon1.w({Key? key})
      : super(
          height: 0,
          width: 26,
          key: key,
        );

  const SpaceIcon1.h({Key? key})
      : super(
          height: 26,
          width: 0,
          key: key,
        );
}

class SpaceIcon2 extends SizedBox {
  const SpaceIcon2({Key? key})
      : super(
          height: 16,
          width: 16,
          key: key,
        );

  const SpaceIcon2.w({Key? key})
      : super(
          height: 0,
          width: 16,
          key: key,
        );

  const SpaceIcon2.h({Key? key})
      : super(
          height: 16,
          width: 0,
          key: key,
        );
}

class SpaceImage1 extends SizedBox {
  const SpaceImage1({Key? key})
      : super(
          height: 144,
          width: 144,
          key: key,
        );

  const SpaceImage1.w({Key? key})
      : super(
          height: 0,
          width: 144,
          key: key,
        );

  const SpaceImage1.h({Key? key})
      : super(
          height: 144,
          width: 0,
          key: key,
        );
}

class SpaceImage2 extends SizedBox {
  const SpaceImage2({Key? key})
      : super(
          height: 108,
          width: 108,
          key: key,
        );

  const SpaceImage2.w({Key? key})
      : super(
          height: 0,
          width: 108,
          key: key,
        );

  const SpaceImage2.h({Key? key})
      : super(
          height: 108,
          width: 0,
          key: key,
        );
}

class SpaceImage3 extends SizedBox {
  const SpaceImage3({Key? key})
      : super(
          height: 55,
          width: 55,
          key: key,
        );

  const SpaceImage3.w({Key? key})
      : super(
          height: 0,
          width: 55,
          key: key,
        );

  const SpaceImage3.h({Key? key})
      : super(
          height: 55,
          width: 0,
          key: key,
        );
}

class SpaceDivider1 extends SizedBox {
  const SpaceDivider1({Key? key})
      : super(
          height: 1,
          width: 1,
          key: key,
        );

  const SpaceDivider1.w({Key? key})
      : super(
          height: 0,
          width: 1,
          key: key,
        );

  const SpaceDivider1.h({Key? key})
      : super(
          height: 1,
          width: 0,
          key: key,
        );
}

class SpacePageMargin extends SizedBox {
  const SpacePageMargin({Key? key})
      : super(
          height: 18,
          width: 18,
          key: key,
        );

  const SpacePageMargin.w({Key? key})
      : super(
          height: 0,
          width: 18,
          key: key,
        );

  const SpacePageMargin.h({Key? key})
      : super(
          height: 18,
          width: 0,
          key: key,
        );
}
