/// Flutter icons SocialMediaIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialMediaIcons
///      fonts:
///       - asset: fonts/SocialMediaIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SocialMediaIcons {
  SocialMediaIcons._();

  static const _kFontFam = 'SocialMediaIcons';
  static const String? _kFontPkg = null;

  static const IconData twitter_square = IconData(0xf081, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_square = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github_square = IconData(0xf092, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xf09b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest = IconData(0xf0d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest_square = IconData(0xf0d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitch = IconData(0xf1e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pinterest_p = IconData(0xf231, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f = IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_play = IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube_square = IconData(0xf431, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
