// Generated by neat
//
// This file has been generated
// Do not modify by hand

part of 'spaces.dart';

// **************************************************************************
// NeatGenerator
// **************************************************************************

class Space1 extends StatelessWidget {
  const Space1()
      : width = 32,
        height = 32;

  const Space1.w()
      : width = 32,
        height = 0;

  const Space1.h()
      : width = 0,
        height = 32;

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space2 extends StatelessWidget {
  const Space2()
      : width = 26,
        height = 26;

  const Space2.w()
      : width = 26,
        height = 0;

  const Space2.h()
      : width = 0,
        height = 26;

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space3 extends StatelessWidget {
  const Space3()
      : width = 18,
        height = 18;

  const Space3.w()
      : width = 18,
        height = 0;

  const Space3.h()
      : width = 0,
        height = 18;

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space4 extends StatelessWidget {
  const Space4()
      : width = 12,
        height = 12;

  const Space4.w()
      : width = 12,
        height = 0;

  const Space4.h()
      : width = 0,
        height = 12;

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space5 extends StatelessWidget {
  const Space5()
      : width = 5,
        height = 5;

  const Space5.w()
      : width = 5,
        height = 0;

  const Space5.h()
      : width = 0,
        height = 5;

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}
