// Generated by neat
//
// This file has been generated
// Do not modify by hand

part of 'spaces.dart';

// **************************************************************************
// NeatGenerator
// **************************************************************************

class Space1 extends StatelessWidget {
  const Space1({Key? key})
      : width = 32,
        height = 32,
        super(key: key);

  const Space1.w({Key? key})
      : width = 32,
        height = 0,
        super(key: key);

  const Space1.h({Key? key})
      : width = 0,
        height = 32,
        super(key: key);

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space2 extends StatelessWidget {
  const Space2({Key? key})
      : width = 26,
        height = 26,
        super(key: key);

  const Space2.w({Key? key})
      : width = 26,
        height = 0,
        super(key: key);

  const Space2.h({Key? key})
      : width = 0,
        height = 26,
        super(key: key);

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space3 extends StatelessWidget {
  const Space3({Key? key})
      : width = 18,
        height = 18,
        super(key: key);

  const Space3.w({Key? key})
      : width = 18,
        height = 0,
        super(key: key);

  const Space3.h({Key? key})
      : width = 0,
        height = 18,
        super(key: key);

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space4 extends StatelessWidget {
  const Space4({Key? key})
      : width = 12,
        height = 12,
        super(key: key);

  const Space4.w({Key? key})
      : width = 12,
        height = 0,
        super(key: key);

  const Space4.h({Key? key})
      : width = 0,
        height = 12,
        super(key: key);

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}

class Space5 extends StatelessWidget {
  const Space5({Key? key})
      : width = 5,
        height = 5,
        super(key: key);

  const Space5.w({Key? key})
      : width = 5,
        height = 0,
        super(key: key);

  const Space5.h({Key? key})
      : width = 0,
        height = 5,
        super(key: key);

  final double width;

  final double height;

  @override
  Widget build(BuildContext context) {
    return SizedBox(width: width, height: height);
  }
}
